name: pytools_small
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.6    # Python version 3.6
    - cartopy       # Geographic plotting toolkit
    - dask          # Parallel processing library
    - ipython       # IPython interpreter and tools
    - jupyter       # Jupyter federation architecture
    - jupyterlab    # Jupyter Lab environment
    - matplotlib    # 2D plotting library
    - netcdf4       # Wrapper for netcdf4
    - numpy         # N-d array and numerics
    - pandas        # Labeled array library
    - scikit-learn  # Macine learning library
    - statsmodels   # Regression/modeling toolkit
    - seaborn       # Statistical visualizations
    - xarray        # N-d labeled array library

